-- MySQL Script generated by MySQL Workbench
-- Sun 21 May 2017 04:43:58 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_product_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_product_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_product_service` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_product_service` ;

-- -----------------------------------------------------
-- Table `ulbora_product_service`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_product_service`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(50) NOT NULL,
  `mfn_id` BIGINT NULL,
  `model` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `overview` BLOB NULL,
  `specifications` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_product_service`.`product_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_product_service`.`product_details` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT NOT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_product_details_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_details_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ulbora_product_service`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_product_service`.`bar_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_product_service`.`bar_code` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `code` VARCHAR(150) NOT NULL,
  `product_details_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_bar_code_product_details1_idx` (`product_details_id` ASC),
  CONSTRAINT `fk_bar_code_product_details1`
    FOREIGN KEY (`product_details_id`)
    REFERENCES `ulbora_product_service`.`product_details` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_product_service`.`product_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_product_service`.`product_options` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT NOT NULL,
  `option_name` VARCHAR(45) NOT NULL,
  `option_value` VARCHAR(100) NOT NULL,
  `product_details_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_product_options_product_details1_idx` (`product_details_id` ASC),
  CONSTRAINT `fk_product_options_product_details1`
    FOREIGN KEY (`product_details_id`)
    REFERENCES `ulbora_product_service`.`product_details` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
